//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
            this.QuizPassQuestions = new HashSet<QuizPassQuestion>();
            this.QuizQuestions = new HashSet<QuizQuestion>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int question_id { get; set; }
        public byte question_type_id { get; set; }
        public short topic_id { get; set; }
        public string question_text { get; set; }
        public byte question_complexity { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual ICollection<QuizPassQuestion> QuizPassQuestions { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
