//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        public QuestionAnswer()
        {
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int answer_id { get; set; }
        public int question_id { get; set; }
        public string answer_text { get; set; }
        public Nullable<byte> answer_order { get; set; }
        public Nullable<bool> is_right { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
    }
}
