//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizType
    {
        public QuizType()
        {
            this.Quizes = new HashSet<Quize>();
        }
    
        public byte quiz_type_id { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<Quize> Quizes { get; set; }
    }
}
