//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizBlock
    {
        public QuizBlock()
        {
            this.QuizPassQuestions = new HashSet<QuizPassQuestion>();
            this.QuizQuestions = new HashSet<QuizQuestion>();
        }
    
        public int quiz_block_id { get; set; }
        public int quiz_id { get; set; }
        public short topic_id { get; set; }
        public Nullable<byte> block_order { get; set; }
        public bool is_random { get; set; }
        public Nullable<byte> question_min_complexity { get; set; }
        public Nullable<byte> question_max_complexity { get; set; }
        public Nullable<byte> question_count { get; set; }
    
        public virtual Quize Quize { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual ICollection<QuizPassQuestion> QuizPassQuestions { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
    }
}
