//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizPassQuestion
    {
        public QuizPassQuestion()
        {
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int quiz_pass_question_id { get; set; }
        public int quiz_pass_id { get; set; }
        public int question_id { get; set; }
        public int quiz_block_id { get; set; }
        public short question_order { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuizBlock QuizBlock { get; set; }
        public virtual QuizPass QuizPass { get; set; }
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
        public virtual UserAnswerScore UserAnswerScore { get; set; }
        public virtual UserTextAnswer UserTextAnswer { get; set; }
    }
}
