//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizVariant
    {
        public QuizVariant()
        {
            this.QuizQuestions = new HashSet<QuizQuestion>();
        }
    
        public int quiz_variant_id { get; set; }
        public int quiz_id { get; set; }
        public byte variant_number { get; set; }
    
        public virtual Quize Quize { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
    }
}
