//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizPass
    {
        public QuizPass()
        {
            this.QuizPassQuestions = new HashSet<QuizPassQuestion>();
        }
    
        public int quiz_pass_id { get; set; }
        public int quiz_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> finish_time { get; set; }
    
        public virtual Quize Quize { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuizPassQuestion> QuizPassQuestions { get; set; }
        public virtual QuizPassScore QuizPassScore { get; set; }
    }
}
