//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuizz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FacebookUsers = new HashSet<FacebookUser>();
            this.QuizPasses = new HashSet<QuizPass>();
            this.QuizPassScores = new HashSet<QuizPassScore>();
            this.UserAnswerScores = new HashSet<UserAnswerScore>();
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string parent_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public bool is_email_confirmed { get; set; }
        public string password_hash { get; set; }
        public string security_stamp { get; set; }
    
        public virtual ICollection<FacebookUser> FacebookUsers { get; set; }
        public virtual ICollection<QuizPass> QuizPasses { get; set; }
        public virtual ICollection<QuizPassScore> QuizPassScores { get; set; }
        public virtual ICollection<UserAnswerScore> UserAnswerScores { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}
