//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eQuizEntities : DbContext
    {
        public eQuizEntities()
            : base("name=eQuizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FacebookUsers> FacebookUsers { get; set; }
        public virtual DbSet<QuestionAnswers> QuestionAnswers { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<QuestionTypes> QuestionTypes { get; set; }
        public virtual DbSet<QuizBlocks> QuizBlocks { get; set; }
        public virtual DbSet<Quizes> Quizes { get; set; }
        public virtual DbSet<QuizPasses> QuizPasses { get; set; }
        public virtual DbSet<QuizPassQuestions> QuizPassQuestions { get; set; }
        public virtual DbSet<QuizPassScores> QuizPassScores { get; set; }
        public virtual DbSet<QuizQuestions> QuizQuestions { get; set; }
        public virtual DbSet<QuizTypes> QuizTypes { get; set; }
        public virtual DbSet<QuizVariants> QuizVariants { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Topics> Topics { get; set; }
        public virtual DbSet<UserAnswers> UserAnswers { get; set; }
        public virtual DbSet<UserAnswerScores> UserAnswerScores { get; set; }
        public virtual DbSet<UserGroups> UserGroups { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTextAnswers> UserTextAnswers { get; set; }
    }
}
