//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizBlocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizBlocks()
        {
            this.QuizPassQuestions = new HashSet<QuizPassQuestions>();
            this.QuizQuestions = new HashSet<QuizQuestions>();
        }
    
        public int quiz_block_id { get; set; }
        public int quiz_id { get; set; }
        public short topic_id { get; set; }
        public Nullable<byte> block_order { get; set; }
        public bool is_random { get; set; }
        public Nullable<byte> question_min_complexity { get; set; }
        public Nullable<byte> question_max_complexity { get; set; }
        public Nullable<byte> question_count { get; set; }
    
        public virtual Quizes Quizes { get; set; }
        public virtual Topics Topics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizPassQuestions> QuizPassQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizQuestions> QuizQuestions { get; set; }
    }
}
