//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizPasses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizPasses()
        {
            this.QuizPassQuestions = new HashSet<QuizPassQuestions>();
        }
    
        public int quiz_pass_id { get; set; }
        public int quiz_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> finish_time { get; set; }
    
        public virtual Quizes Quizes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizPassQuestions> QuizPassQuestions { get; set; }
        public virtual QuizPassScores QuizPassScores { get; set; }
    }
}
