//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestions
    {
        public int question_id { get; set; }
        public int quiz_block_id { get; set; }
        public Nullable<int> quiz_variant_id { get; set; }
        public byte question_score { get; set; }
        public Nullable<short> question_order { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual QuizBlocks QuizBlocks { get; set; }
        public virtual QuizVariants QuizVariants { get; set; }
    }
}
