//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizPassQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizPassQuestions()
        {
            this.UserAnswers = new HashSet<UserAnswers>();
        }
    
        public int quiz_pass_question_id { get; set; }
        public int quiz_pass_id { get; set; }
        public int question_id { get; set; }
        public int quiz_block_id { get; set; }
        public short question_order { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual QuizBlocks QuizBlocks { get; set; }
        public virtual QuizPasses QuizPasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnswers> UserAnswers { get; set; }
        public virtual UserAnswerScores UserAnswerScores { get; set; }
        public virtual UserTextAnswers UserTextAnswers { get; set; }
    }
}
